services:
  - type: web
    name: macro-tracker-api
    runtime: python
    buildCommand: ""
    startCommand: uvicorn macro_tracker_backend.main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: macro-tracker-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
    plan: free
